services:
  - type: web
    name: btc-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    runtime: python3.10
    envVars:
      - key: BINANCE_API_KEY
        value: your_api_key_here
      - key: BINANCE_API_SECRET
        value: your_api_secret_here
      - key: TELEGRAM_TOKEN
        value: your_telegram_token_here
      - key: TELEGRAM_CHAT_ID
        value: your_chat_id_here
