services:
  - type: web
    name: btc-trading-bot
    env: python
    buildCommand: |
      echo "python-3.10.13" > runtime.txt
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BINANCE_API_KEY
        value: your_api_key_here
      - key: BINANCE_API_SECRET
        value: your_api_secret_here
      - key: TELEGRAM_TOKEN
        value: your_telegram_token_here
      - key: TELEGRAM_CHAT_ID
        value: your_chat_id_here
